export const RESULT_IN_PARSE = [
  "C++ a statically typed compiled",
  "programming language famous for its",
  "widespread use in software",
  "infrastructure and Infamous for its",
  "steep learning curve it was created in",
  "1979 by bej Strauss at AT&amp;T Bell Labs he",
  "was inspired by the object-oriented",
  "nature of simula but needed a language",
  "with a high performance of c and thus C",
  "with classes was born it&#39;s designed as a",
  "suet of C which means that virtually any",
  "c program is also a valid C++ program",
  "but it also adds zero overhead",
  "abstractions such as object-oriented",
  "patterns like polymorphism encapsulation",
  "and inheritance today it&#39;s used in a",
  "wide variety of systems with constrained",
  "memory demands like the Unreal Engine",
  "for AAA video games programs like Adobe",
  "After Effects that were used to edit",
  "this video databases like MySQL and",
  "mongodb embedded systems like the",
  "display on your smart toaster and is",
  "used to implement much of our low-level",
  "infrastructure like language compilers",
  "and virtual machines it&#39;s so popular",
  "because it provides low-level memory and",
  "Hardware control like C but with highle",
  "abstractions like classes and Mark",
  "pointers C++ makes it harder to shoot",
  "yourself in the foot but when you do",
  "it&#39;ll blow your whole leg off to get",
  "started install a C+ plus compiler like",
  "GCC or clang then create a file ending",
  "in CPP include IO stream from the",
  "standard library to handle input and",
  "output your code will start executing",
  "from the main function to print hello",
  "world we simply use standard character",
  "output followed by the bit y shift left",
  "operator and a string literal we can get",
  "rid of this STD though by adding a",
  "namespace to the top of the file now if",
  "we want to create a string variable we",
  "can do so by typing it as an array of",
  "characters however if we include string",
  "from the standard Library we can use the",
  "string type instead the real game",
  "changer though is the fact that C++",
  "supports object-oriented programming",
  "with classes a class is just a blueprint",
  "for an object inside a class you can",
  "Define attributes and methods that will",
  "be private by default or make them",
  "public by adding them under the public",
  "specifier it&#39;s also possible to Define",
  "methods outside the class definition",
  "using a double colon methods can also be",
  "defined multiple times with different",
  "parameters which is known as overloading",
  "and is a form of polymorphism in",
  "addition we can Define Constructors and",
  "destructors to run code when an object",
  "is created or destroy classes also",
  "support inheritance allowing developers",
  "to more efficiently share logic",
  "throughout a program to instantiate an",
  "object type the class name followed by",
  "the name of your object and optionally",
  "any parameters for the Constructor when",
  "it comes to memory we could manage",
  "everything manually with pointers and",
  "references however tools like unique",
  "pointer can get the job done in a way",
  "that&#39;s easier and safer by ensuring that",
  "only one object can be allocated to",
  "memory now to run your code open up the",
  "terminal and use a tool like clang ++ to",
  "compile it this has been C++ in 100",
  "seconds hit the like button and",
  "subscribe if you want to see more short",
  "videos like this thanks for watching and",
  "I will see you in the next one",
];

export const TITLE_AND_DESCRIPTION =
  '[\n  {"title": "C++ Overview", "content": ["A statically typed, compiled programming language.", "Famous for its widespread use in software infrastructure.", "Infamous for its steep learning curve."]},\n  {"title": "C++ History", "content": ["Created in 1979 by Bjarne Stroustrup at AT&T Bell Labs.", "Inspired by the object-oriented nature of Simula.", "Designed as a superset of C."]},\n  {"title": "C++ Features", "content": ["Zero-overhead abstractions such as object-oriented patterns like polymorphism, encapsulation, and inheritance.", "Provides low-level memory and hardware control like C, but with higher abstractions like classes and smart pointers."]},\n  {"title": "Getting Started with C++", "content": ["Install a C++ compiler like GCC or Clang.", "Create a file ending in .cpp and include <iostream> from the standard library.", "Start coding in the main function."]},\n  {"title": "C++ Programming Concepts", "content": ["Classes support object-oriented programming.", "Methods can be defined inside or outside the class definition.", "Constructors and destructors can be used to run code when an object is created or destroyed."]}\n]';

export const CONVERT_TEXT_ARRAY =
  'C++ is a statically typed, compiled programming language famous for its widespread use in software infrastructure and infamous for its steep learning curve. It was created in 1979 by Bjarne Stroustrup at AT&T Bell Labs. He was inspired by the object-oriented nature of Simula but needed a language with the high performance of C, and thus C with classes was born. It’s designed as a superset of C, which means that virtually any C program is also a valid C++ program. However, it also adds zero-overhead abstractions such as object-oriented patterns like polymorphism, encapsulation, and inheritance.   Today, it’s used in a wide variety of systems with constrained memory demands, such as the Unreal Engine for AAA video games, programs like Adobe After Effects that were used to edit this video, databases like MySQL and MongoDB, and embedded systems like the display on your smart toaster. It is also used to implement much of our low-level infrastructure, including language compilers and virtual machines.   C++ is popular because it provides low-level memory and hardware control like C, but with higher abstractions like classes and smart pointers. C++ makes it harder to shoot yourself in the foot, but when you do, it’ll blow your whole leg off.   To get started, install a C++ compiler like GCC or Clang. Then create a file ending in .cpp and include <iostream> from the standard library to handle input and output. Your code will start executing from the main function. To print "Hello, World," we simply use standard character output followed by the bitwise shift left operator and a string literal. We can get rid of this "std" prefix by adding a namespace to the top of the file.   If we want to create a string variable, we can do so by typing it as an array of characters. However, if we include <string> from the standard library, we can use the string type instead. The real game changer, though, is the fact that C++ supports object-oriented programming with classes. A class is just a blueprint for an object. Inside a class, you can define attributes and methods that will be private by default or make them public by adding them under the public specifier.   It’s also possible to define methods outside the class definition using a double colon. Methods can also be defined multiple times with different parameters, which is known as overloading and is a form of polymorphism. In addition, we can define constructors and destructors to run code when an object is created or destroyed. Classes also support inheritance, allowing developers to more efficiently share logic throughout a program.   To instantiate an object, type the class name followed by the name of your object and optionally any parameters for the constructor. When it comes to memory, we could manage everything manually with pointers and references; however, tools like unique_ptr can get the job done in a way that’s easier and safer by ensuring that only one object can be allocated to memory.   Now, to run your code, open up the terminal and use a tool like clang++ to compile it. This has been C++ in 100 seconds. Hit the like button and subscribe if you want to see more short videos like this. Thanks for watching, and I will see you in the next one!';

export const CONTENT_ARRAY_TEXT =
  '[\n  {"title": "C++ Overview", "content": ["A statically typed, compiled programming language.", "Famous for its widespread use in software infrastructure.", "Infamous for its steep learning curve."]},\n  {"title": "C++ History", "content": ["Created in 1979 by Bjarne Stroustrup at AT&T Bell Labs.", "Inspired by the object-oriented nature of Simula.", "Designed as a superset of C."]},\n  {"title": "C++ Features", "content": ["Zero-overhead abstractions such as object-oriented patterns like polymorphism, encapsulation, and inheritance.", "Provides low-level memory and hardware control like C, but with higher abstractions like classes and smart pointers."]},\n  {"title": "Getting Started with C++", "content": ["Install a C++ compiler like GCC or Clang.", "Create a file ending in .cpp and include <iostream> from the standard library.", "Start coding in the main function."]},\n  {"title": "C++ Programming Concepts", "content": ["Classes support object-oriented programming.", "Methods can be defined inside or outside the class definition.", "Constructors and destructors can be used to run code when an object is created or destroyed."]}\n]';
